# Python 3 script for parsing a JSON file generated by Realm Studio
# from a realm database for the JusTalk app for iOS (may work for Android
# also but not yet tested.  Working on version 8.9.44 for iOS
# Authored by Aaron Dee Roberts, MSP
# https://github.com/trunk-d-monkey

'''
   -h or --help   : This message (with nothing further)
   -o or --output : Output file (Defaults if nothing entered)
   -i or --input  : Input JSON file
   -f or --folder : Folder containing file cache
   
   This application will parse the conversations from the JusTalk app
   (tested on iOS) into an SQLite database for analysis. Files and 
   folders it needs are:
   
   Main Realm Database: 
      [app container]/data/[user id]/realm/[user id].realm
   
   Cache Folder:
      [app container]/data/imageCache/temp
   
   INSTRUCTIONS: Export the above file and folder.  Use RealmStudio to
   export the realm database AS a JSON file. You can then point the 
   input and folder arguments to process the file. 
   
   EX: python parse_justalk.py -i D:\JUSTALK_DATA\9999_62135600.json 
   -f D:\JUSTALK_DATA\data\imageCache\temp
------------------------------------------------------------------------
'''

import json
import sys
import os
import sqlite3
from sqlite3 import OperationalError
import platform
import hashlib
import subprocess
import base64

def check_integer(l_input):

	try: 
		x = int(l_input)
		l_int = True
	except: l_int = False
	
	return l_int

# Make a shorter string from the <class 'type'> restult of type()
def crop_class(lc_class):
	
	ls_class = str(lc_class)
	l_sep = '\''
	li_start = ls_class.find(l_sep) + 1
	li_end = ls_class.rfind(l_sep)
	ls_type = ls_class[li_start:li_end]
	return ls_type

# Parse the file
def elements_build(ls_file):

	f = open(s_inputfile,'r', encoding='utf-8')

	fdata = f.read() # Read the file into memory
	f.close() # Close the file
	del f # Release the variable, leaving fdata

	l_json = json.loads(fdata) # put the json data from the file into a list (l_json)
	ld_json = {} # Make the dictionary to put contents into with index of item
	ll_temp = [] # Temp list for dictionary entries

	i_count = 0 # Set the counter to display the index 

	for x in l_json:
		ll_temp.append(x) # Add the content to the dic list
		ls_type = crop_class(type(x)) # Make a nicer format in a string
		ll_temp.append(ls_type) # Add the TYPE
		ll_temp.append(i_count) # Add the index number (matches key but smoother calling)
		ld_json[i_count] = ll_temp # Add the list as a value to the key
		ll_temp = []
		i_count += 1

	del l_json # Release the list and keep the dictionary 

	return ld_json # Return the dictionary list index : content, type, list index

# PROCESS THE ELEMENTS OF THE OBJECT
def elements_process(ld_json, ls_output, ls_e_return): 
	
	ld_tables = ld_json[0][0] # Get the tables (First item in list)
	
	li_rec_level = 0 # Level deep of element
	ll_elements = [] # Empty list of elements
	lb_fields = False
	ll_tables = [] # Holds list of tables WITH actual contents. Used to build ONLY needed tables.
	ld_tables_fill = {} # Holds dictionary of tables WITH actual contents. Used to build ONLY needed tables
	
	ld_tables_fields = {} # For tables list with fields

	# Cycle through the tables (root object) and get the elements
	for lx in ld_tables:
		lb_fields = False # Reset to false for next table
		ll_fields = [] # Reset the fields
		ls_table = lx # Get the table name
		ls_index = ld_tables[lx] # Get the index of the object list=
		ll_elements_locations = ld_json[int(ls_index)][0] # Get the list of locations for each table

		if len(ll_elements_locations) > 0:
			ld_tables_fill[lx] = ld_tables[lx] # Append current table to list of tables WITH content
			if lb_fields == False: # If level 1 fields not entered already
				li_first = int(ll_elements_locations[0])
				ld_first = ld_json[li_first][0]
				
				lz_type = None
				
				for lz in ld_first.keys():
					ll_fields.append(lz) # Append the field to the list
				
				lb_fields = True
	
		ld_tables_fields[lx] = ll_fields # Add the dictionary of fields to the corresponding table regardless of amount of data
		
	# ld_tables_fill is list of tables with contents to be build.
	
	# TIME TO BUILD THE TABLES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	ls_table_sql = '' # Pre assigne variable
	
	# Open the connection to a database
	sql_con = sqlite3.connect(ls_output)
	sql_con.row_factory = sqlite3.Row # MUST come before the connection
	sql_cur = sql_con.cursor()
	
	# Roll through the fields for each table and build the query to build the table.
	for lx in ld_tables_fill:
		# begin building query anew
		ls_table_sql = f"""CREATE TABLE IF NOT EXISTS {lx} ("""
		lx_fields = ld_tables_fields[lx] # Get list of fields
		# Cycle through list of fields
		lx_i_count = 0 # Counter to only put comma IF above 0
		for ls_field in lx_fields:
			if lx_i_count > 0: ls_comma = ', \n'
			else: ls_comma = '\n'
			ls_line = f'{ls_comma}"{ls_field}" VARCHAR'
			ls_table_sql = ls_table_sql + ls_line
			lx_i_count += 1
			
		ls_table_sql = ls_table_sql + ');'

		try:
			sql_cur.execute(ls_table_sql)
		except sqlite3.OperationalError as e:
			print(f'Error in QUERY: {e} for table {lx}')
			input('Press ENTER to continue')
			
			if ls_e_return == 's': ls_e_return = f'Error in QUERY: {e} for table {lx}'
			else: ls_e_return = ls_e_return + f', Error in QUERY: {e} for table {lx}'

		# Commit the tables that were built
		sql_con.commit()
	
	# Free up some variables since this is not in a separate function
	del ls_table_sql
	del ls_line
	del lx_i_count
	del ls_field
	del ll_elements_locations
	
	# Cycle throuth ld_tables and get only those in ld_tables_fill with their index
	for lx_table in ld_tables_fill:
		# Get the list of indexes where elements are
		ll_elements = ld_json[int(ld_tables_fill[lx_table])][0]
		# ll_elements is a list of indexes for where the table elements are
		for l_index in ll_elements:
			li_index = int(l_index) # Make it an integer for comparison since they are stored in strings. 
			lv_element = ld_json[li_index][0] # Get the element
			lt_element = type(lv_element) # Determine the element type
			
			if lt_element == dict: # SHOULD be dictionary but just in case
				ls_sql_fields = '' # For holding fields
				ll_sql_fields = [] # list for holding fields to be joined 
				ls_sql_values = '' # For holding values
				ll_sql_values = []
				
				for l_part in lv_element:
					ll_sql_fields.append(f'"{l_part}"')
					l_part_value = lv_element[l_part]
					
					ls_wrapper = '' # Wrapper for putting single quote on dictionary items as strings
					
					if type(l_part_value) == str: 
						# Check and if the string is an integer, get the content for the field
						lb_check = check_integer(l_part_value) # Check if element may be index
						if lb_check == True: # If it IS a string integer, check if it's in the elements
							if int(l_part_value) in ld_json:
								l_part_value_temp = ld_json[int(l_part_value)][0]
								
								if type(l_part_value_temp) == dict: 
									l_part_value = str(l_part_value_temp)
									l_part_value_temp = None
								else: l_part_value = l_part_value_temp
								
								# Set the wrapper
								if '"' in l_part_value: ls_wrapper = "'"
								else: ls_wrapper = '"'
								
						ll_sql_values.append(f'({ls_wrapper}{l_part_value}{ls_wrapper})') # Append to the list
					elif isinstance(l_part_value, type(None)): ll_sql_values.append('NULL') # Works
					else: ll_sql_values.append(str(l_part_value))
					
					ls_sql_fields = ','.join(ll_sql_fields)
					ls_sql_values = ','.join(ll_sql_values)
					
					# We now have the lists to put together in the query. 
					
					l_query = f'''INSERT INTO {lx_table} ({ls_sql_fields}) VALUES ({ls_sql_values})'''

				sql_cur.execute(l_query)
	
	# BUILD THE JUSTALK CONVERSATIONS TABLE IN STEPS. 
	
	sql_cur.execute(l_query)
	
	# -- PARTICIPANT NAMES
	l_query = '''
	CREATE TEMP TABLE IF NOT EXISTS CONTACTS AS
	SELECT DISTINCT 
	ServerFriend.uid AS UID, ServerFriend.name AS NAME,
	ServerFriend.justalkId AS JUSTALK_ID, ServerFriend.nickName AS NICKNAME,
	"(" || (CASE WHEN ServerFriend.name IS NOT NULL THEN "Name: " || ServerFriend.name || ", " ELSE "" END) || 
	(CASE WHEN ServerFriend.justalkId IS NOT NULL THEN "ID: " || ServerFriend.justalkId || ", " ELSE "" END) ||
	(CASE WHEN ServerFriend.nickName IS NOT NULL THEN "Nickname: " || ServerFriend.nickName || ")" ELSE ")" END) 
	AS CONTACT_INFO
	FROM ServerFriend'''

	sql_cur.execute(l_query)
	
	# -- ACCOUNT USER_TEMP
	l_query = '''
	CREATE TEMP TABLE IF NOT EXISTS AU_S1 AS
	SELECT DISTINCT
	GROUP_CONCAT(DISTINCT CallLog.senderName) AS DEVICE_USER,
	CASE CallLog.incoming
	   WHEN 1 THEN 'INCOMING'
	   WHEN 0 THEN 'OUTGOING'
	END AS DIRECTION
	FROM CallLog 
	WHERE CallLog.senderName IS NOT NULL
	AND CallLog.incoming = 0
	GROUP BY callLog.senderName'''
	
	sql_cur.execute(l_query)

	# -- ACCOUNT USER
	l_query = '''
	CREATE TEMP TABLE IF NOT EXISTS ACCOUNT_USER AS
	SELECT AU_S1.DEVICE_USER, AU_S1.DIRECTION, CONTACTS.CONTACT_INFO
	FROM AU_S1
	LEFT JOIN CONTACTS ON AU_S1.DEVICE_USER LIKE CONTACTS.NICKNAME'''

	sql_cur.execute(l_query)
	
	# CallLog.type 
	# 0 = Audio, 1 = Video, 2 = Text, 17 = Sticker
	# 6 = Image, 18 = GIF, 15 = Audio File, 21 = Emoji
	# 200 = JusTalk sales, 19 = Doodle, 7 = Automated message
	
	# 14 = Unknown EX: {"MtcImMsgIdKey":741,"MtcImImdnIdKey":"3761ED52-5F86-498F-B52C-197F5C04767D"}
	# 3000 = Unknown
	
	# -- MATCH THE MESSAGES TO THE ACCOUNT_USER AND CONTACTS
	l_query = '''
	CREATE TABLE IF NOT EXISTS A_MESSAGES_DATA AS
	SELECT
	CallLog.ROWID AS R_ID,
	CallLog.uid AS CONVERSATION_UID,
	CallLog.callId AS CALL_ID,
	CASE 
	   WHEN CallLog.startTime IS NOT 0 AND CallLog.startTime IS NOT NULL
		  THEN datetime(CallLog.startTime,'unixepoch')
	   ELSE CallLog.startTime
	END AS START_UTC,
	CASE 
	   WHEN CallLog.endTime IS NOT 0 and CallLog.endTime IS NOT NULL
		  THEN datetime(CallLog.endTime,'unixepoch')
		  ELSE CallLog.endTime
	END AS END_UTC,
	CallLog.type AS TYPE_CODE,
	CASE CallLog.type
	   WHEN 0 THEN 'Audio Call'
	   WHEN 1 THEN 'Video Call'
	   WHEN 2 THEN 'Text Message'
	   WHEN 15 THEN 'Audio File'
	   WHEN 6 THEN 'Image'
	   WHEN 21 THEN 'Emoji'
	   WHEN 18 THEN 'GIF'
	   WHEN 17 THEN 'Sticker'
	   WHEN 19 THEN 'Doodle'
	   WHEN 200 THEN 'JusTalk Sales'
	   WHEN 7 THEN 'Automated Message'
	   ELSE CallLog.type
	END AS TYPE,
	CASE CallLog.incoming
	   WHEN 1 THEN 'INCOMING'
	   WHEN 0 THEN 'OUTGOING'
	END AS DIRECTION,
	CallLog.senderUid || " " || SENDERS.CONTACT_INFO AS SENDER_UID_INFO,
	datetime(CallLog.timestamp/1000,'unixepoch') AS TIMESTAMP_UTC,
	CASE 
		WHEN CallLog.senderName IS NOT NULL
			THEN CallLog.senderName
		ELSE "(NULL_SYSTEM)"
	END SENDER,
	CASE CallLog.incoming
		WHEN 1 THEN "FROM: " || CONTACTS.CONTACT_INFO
		WHEN 0 THEN "TO: " || CONTACTS.CONTACT_INFO
	END AS CONTACT_DATA,
	CASE 
	   WHEN CallLog.type = 2 THEN CallLog.content
	   WHEN CallLog.type = 6 THEN 'IMAGE: ' || CallLog.content
	   WHEN CallLog.type = 7 THEN 'AUTOMATED MESSAGE: ' || CallLog.content
	   WHEN CallLog.type = 1 THEN 'VIDEO CALL: ' || time(CallLog.endTime - CallLog.startTime, 'unixepoch') 
	   WHEN CallLog.type = 0 THEN 'AUDIO CALL: ' || time(CallLog.endTime - CallLog.startTime, 'unixepoch') 
	   WHEN CallLog.type = 18 THEN 'GIF: ' || CallLog.content
	   WHEN CallLog.type = 15 THEN 'AUDIO FILE: ' || CallLog.content
	   WHEN CallLog.type = 19 THEN 'DOODLE: ' || CallLog.content
	   WHEN CallLog.type = 17 THEN 'STICKER: ' || CallLog.content
	   WHEN CallLog.type = 21 THEN 'EMOJI: ' || CallLog.content
	   WHEN CallLog.type = 200 THEN 'JUSTALK SALES: ' || CallLog.content
	   ELSE CallLog.content
	END AS CONTENT,

	CAST(NULL AS BLOB) AS CACHE_FILE_BLOB_DATA,
	CAST(NULL AS BLOB) AS CACHE_THUMB_BLOB_DATA,
	CAST(NULL AS TEXT) AS CACHE_FILE_NAME,
	CAST(NULL AS TEXT) AS CACHE_FILE_MD5,
	CAST(NULL AS TEXT) AS CACHE_THUMB_NAME,
	CallLog.imdnId AS IMDN_ID,
	CallLog.userData AS USER_DATA, CallLog.repliedImdnId AS REPLIED_IMDN_ID,
	CallLog.repliedLog AS REPLIED_LOG, CallLog.replyCount AS REPLY_COUNT,
	CallLog.reactedImdnId AS REACTED_IMDN_ID, CallLog.reactLogs AS REACT_LOGS,
	CallLog.content AS CONTENT_ORIGINAL
	FROM CallLog
	LEFT JOIN ACCOUNT_USER
	ON ACCOUNT_USER.DIRECTION = DIRECTION 
	AND ACCOUNT_USER.DEVICE_USER = CallLog.senderName
	LEFT JOIN CONTACTS
	ON CONTACTS.UID = CallLog.uid
	LEFT JOIN CONTACTS AS SENDERS
	ON SENDERS.UID = CallLog.senderUid
	ORDER BY TIMESTAMP_UTC'''	

	sql_cur.execute(l_query)
	
	# Now query and roll through content with attachments in A_MESSAGES_DATA
	l_query = '''
	SELECT R_ID, CONTENT_ORIGINAL,CACHE_FILE_NAME, CACHE_FILE_MD5, CACHE_FILE_BLOB_DATA,
	CACHE_THUMB_NAME, CACHE_THUMB_BLOB_DATA
	FROM A_MESSAGES_DATA ORDER BY R_ID'''
	
	sql_cur.execute(l_query)
	
	# Get the records
	l_records = sql_cur.fetchall()
	
	# Cycle through all the records populating BLOBs where needed. 
	for row in l_records:
		# Pre assign in case contents are NOT json but contain "md5"
		# May be redundent but here for insurance.
		l_md5 = None
		l_cache_fn = None
		l_cache_fn_data = None
		l_thumbnail_fn = None
		l_thumb_data = None
		l_rid = None
		
		lb_error = False # Error to set if JSON decoding error
		
		l_rid = row['R_ID']
		l_content = row['CONTENT_ORIGINAL']
		if l_content != None:
			# Get the file attachment information (base64 of the BINARY MD5)
			# The programmers for some reason are storing the cache file name, not by the file name
			# but the binary MD5... yep, the hexidecimal in BINARY which is THEN encoded base64
			# and stored in the content.  
			if 'md5' in l_content:
				try: # Here because if the contents are NOT JSON, the json.loads() will error.  It will skip this section.
					l_json = json.loads(l_content)
					l_b64md5 = l_json.get('md5')
					if l_b64md5 != None:
						l_md5 = base64.b64decode(l_b64md5).hex() # Get the printable hex from bytes
						lt = d_hashes.get(l_md5) # Get the cache file name list
						l_cache_fn = lt[1] # File NAME for storage
						l_cache_fp = lt[0] # File FULL PATH for Binary import
						
						# Get the file DATA
						x = open(l_cache_fp, 'rb') # Open the file
						l_cache_fn_data = x.read() # Read the data
						x.close() # Close the file
						del x

					# Get the thumbnail if there is one
					l_thumbnail_fn = l_json.get('localThumbnail')

					if l_thumbnail_fn != None:
						l_thumb_path = d_files.get(l_thumbnail_fn) # Get the full path of the thumbnail
						
						# Get the data from the thumbnail file
						x = open(l_thumb_path, 'rb')
						l_thumb_data = x.read()
						x.close()
						del x
					lb_error = False
					
				except:
					lb_error = True
				
				# Input the data IF there is not a JSON error
				if lb_error == False:				
					l_query = f'''
					UPDATE A_MESSAGES_DATA SET
					CACHE_FILE_MD5 = "{l_md5}",
					CACHE_FILE_NAME = "{l_cache_fn}",
					CACHE_THUMB_NAME = "{l_thumbnail_fn}"
					WHERE R_ID = "{l_rid}"'''

					sql_cur.execute(l_query)
				
				# Add the BLOBs.  Has to be done with placeholders.
				# Need ALL placeholders or ALL variable insterts like above
					l_input_data = (l_cache_fn_data, l_thumb_data, l_rid)
				
					l_query = f'''
					UPDATE A_MESSAGES_DATA SET CACHE_FILE_BLOB_DATA = ?,
					CACHE_THUMB_BLOB_DATA = ? WHERE R_ID = ?'''
				
					sql_cur.execute(l_query, l_input_data)
				
		# Clear the variables for the next round.  If we don't do this
		# You'll have stuff put in the wrong places
		l_md5 = None
		l_cache_fn = None
		l_cache_fn_data = None
		l_thumbnail_fn = None
		l_thumb_data = None
		l_rid = None

	
	# PUT YOUR TOYS AWAY
	sql_con.commit()
	sql_con.close()

	return ls_e_return
	

# GET THE ARGUMENTS
def get_arguments():
	
	lb_error = False
	lb_help = False
	l_arguments = []
	d_variables = {}
	
	# This is the help to print if the -h or --help is entered somewhere on the command line
	ls_help = '''
------------------------------------------------------------------------
------------------- JUSTALK CONVERSATIONS PARSER -----------------------
----------------- HELP DOCUMENTATION FOR ARGUMENTS ---------------------
------------------------------------------------------------------------

   -h or --help   : This message (with nothing further)
   -o or --output : Output file (Defaults if nothing entered)
   -i or --input  : Input JSON file
   -f or --folder : Folder containing file cache
   
   This application will parse the conversations from the JusTalk app
   (tested on iOS) into an SQLite database for analysis. Files and 
   folders it needs are:
   
   Main Realm Database: 
      [app container]/data/[user id]/realm/[user id].realm
   
   Cache Folder:
      [app container]/data/imageCache/temp
   
   INSTRUCTIONS: Export the above file and folder.  Use RealmStudio to
   export the realm database AS a JSON file. You can then point the 
   input and folder arguments to process the file. 
------------------------------------------------------------------------'''
	
	# Dictionary to hold arguments.  Type and TWO arguments are required. 
	# Modifiy this as needed to hold the arguments needed.  If other things
	# are added to the commmand line by the user or switches without 
	# anything following, they will be ignored. 
	# Any argument following the items in the list will be put into a new
	# dictionary 'd_variables' so that they can be assigned.
	# EX: -d MyFolder will be put into the dictionary as 
	#    {'directory': 'MyFolder'}
	# which can be called by s_directory = d_variables.get('directory')
	
	d_arguments = {
	'help':['-h', '--help'], # Leave the HELP here.  The other items an be changed.
	'output':['-o', '--output'],
	'input':['-i', '--input'],
	'folder':['-f', '--folder']
	}
	
	i_arg = len(sys.argv) # Get number of arguments
	i_arg_count = 0
	
	# Get a list of arguments
	for x in range(1, i_arg):
		l_arguments.append(sys.argv[x])

	# If an argument is one of the helps, stop and print help documentation.
	for x in l_arguments:
		# Check each argument in the list to see if help is requested. 
		if x.lower() == '-h' or x.lower() == '--help':
			lb_help = True
			print(ls_help)
			print()

	if lb_help == False:
		i_index = 0
		for x in l_arguments: # Cycle through list of arguments
			for i in d_arguments.items(): # Cycle through dictionary items (touples)
				if x == i[1][0] or x == i[1][1]:  # Compare if argument matches value
					if (i_index + 2) < i_arg: # Make sure the end is within range to avoid errors
						d_variables[i[0]] = l_arguments[i_index + 1] # If it's within range, assign key/value
			i_index += 1 # Add to the index.
	
	# Variables can now be assigned with the 'd_variables' dictionary.
	
	return d_variables


# Get the list of files
def make_file_list(l_s_root):
	
	ll_files = [] # List to hold file pairs
	ll_fp = [] # Sub list to hold fullpath(f) and partialpath(p)
	ld_files = {} # Empty dictionary to hold paths by file names
	
	for root, dirs, files in os.walk(l_s_root):
		for f in files:
			ll_fp = [] # Clear the sub list
			full_path = os.path.join(root, f)
			ll_files.append([full_path, f, root])
			ld_files[f] = full_path
	
	return ll_files, ld_files

# Hash the data and write it to a TSV file
def hash_files(ll_files):

	ld_hashes = {} #Empty dictionary to put things in. 
	
	chunk_size = 4096
	
	ls_hash = 'md5'
	
	# Hash the files while printing output
	for ll_item in ll_files:
		
		l_item = ll_item[0] # Take only the full path from ll_item for hashing the file contents

		# Set hashlibs - Create new for EACH loop otherwise it compounds
		if ls_hash == 'md5': do_hash = hashlib.md5()
		if ls_hash == 'sha256': do_hash = hashlib.sha256()
		if ls_hash == 'sha1': do_hash = hashlib.sha1()
		
		# Open file for binary read
		f = open(l_item, 'rb')
		
		# Do it in chunks to make it do LARGE files easier
		while chunk := f.read(chunk_size):
			do_hash.update(chunk)
		
		# Also works as above but simpler, though longer
		# ~ while True:
			# ~ chunk = f.read(chunk_size)
			# ~ if not chunk:
				# ~ break
			# ~ do_hash.update(chunk)
			
		# Give the total in uppercase
		hs = do_hash.hexdigest()
		
		# Add it to the dictionary
		ld_hashes[hs] = ll_item
		
		# Close the file being read
		f.close()

	# Returning dictionary with keys as MD5 hashes, then list with 0:fullpath 1:filename
	return ld_hashes

# ======================================================================
# BEGIN NON FUNCTIONS CODE ---------------------------------------------

s_root = os.getcwd()
s_separator = '========================================================='

# Get the arguments
d_variables = get_arguments()

s_inputfile = d_variables.get('input')
s_inputfolder = d_variables.get('folder')

if s_inputfile == None or s_inputfile == '':
	print('No input file was specified')
	sys.exit()
if os.path.isfile(s_inputfile) == False:
	print(f'File {s_inputfile} does not exist.  Exiting.')
	sys.exit()

s_output = d_variables.get('output')

if s_output == None or s_output == '':
	s_output = s_inputfile + '_.db'

print(s_separator)
print(f'Using {s_inputfile} outputting to {s_output}')

# Make a list of cache files
print(f'Making a list of files in {s_inputfolder}')
l_files, d_files = make_file_list(s_inputfolder)

# Hash the list of cache files and put in a dictionary
print('Hashing the input folder contents')
d_hashes = hash_files(l_files)

s_e_return = '' # Assign the error list 

# Build the dictionary from the file contents
print(f'Parsing JSON input file into it\'s elements: {s_inputfile}')
d_json = elements_build(s_inputfile) 

# Process the json elements and cache files into a SQLite database
print(f'Processing the elements and cache files into {s_output}')
s_e_return = elements_process(d_json, s_output, s_e_return)

if s_e_return == '': print(f'Finished. Check {s_output} for data')
else: print(f'ERRORS! {s_e_return}')
